controller_list:
  - name: fake_tgr_arm_controller
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
initial:  # Define initial robot poses.
  - group: tgr_arm
    pose: zero