#controller_manager_ns: controller_manager
controller_list:
 - name: bliss/bliss_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - joint1
     - joint2
     - joint3
     - joint4
     - joint5
     - joint6
initial:  # Define initial robot poses.
  - group: manipulator
    pose: home